server:
  port: 9001

spring:
  application:
    name: provider-01

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoint:
    web:
      exposure:
        include: "*"