server:
  port: 8001

spring:
  application:
    name: consumer-01

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoint:
    web:
      exposure:
        include: "*"